version: '3'

services:
  nginx:
    build: ./nginx
    ports:
      - "3000:80"
    depends_on:
      - backend
      - organizer
    restart: always

  backend:
    build: ./backend
    restart: always
    

  organizer:
    build: ./organizer
    restart: always
   
  





 


