version: '3'

services:
  nginx:
    build: ./nginx
    ports:
      - "3000:80"
    depends_on:
      - backend
      - organizer

  backend:
    build: ./backend
    depends_on:
      - postgres
    ports:
      - 9000:9000
  

  organizer:
    build: ./organizer
 

  postgres:
    build: ./postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
  
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
