version: "3.8"
services:
  postgres:
    build:
      context: ./postgres
      dockerfile: ./Dockerfile
    container_name: postgres
    ports:
      - "5432:5432"
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    container_name: backend
    ports:
      - "9000:9000"
    restart: always
    volumes:
      - ./backend:/backend
    depends_on:
      - postgres

  organizer:
    build:
      context: ./organizer
      dockerfile: ./Dockerfile
    container_name: organizer
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - backend
